### ISSUE TITLE
ONION::clasterUsingOntology

### ISSUE THREAD

**Issue by wjurkowski** [wjurkowski/ONION#19]
I have following problem with running some Chebi IDs:

When this line is included (CHEBI:73705) 
73705   1.1166  0.6362  0.4674  3.8548  0.4866  0.5095  0.7578  0.2586  0.8921  2.1589  0.9961  0.7193  8.6515  7.218

i get:

> clusteredSmallMolecules <- ONION::clasterUsingOntology(pathToFile = pathToFileWithChebiIds, header = TRUE, ontologyRepresentatnion = ONION::firstExistsInReactomeChebiOntology)
Error in grep(ChEBIId, chEBIToReactomeLowestLevel$V1) : 
  invalid 'pattern' argument

problem disappears when the line is deleted

**Comment by wjurkowski** [comment]
my fear is, this is a result of specific Chebi ID not present in the lookup table we are currently using to find reactions? (Chebi2Reactome)

**Comment by koralgooll** [comment]
Fixed. Now find parent for that Chebi id. Problem was with empty DF in for loop.

**Comment by wjurkowski** [comment]
I still get 
 Error in grep(ChEBIId, chEBIToReactomeLowestLevel$V1) : 
  invalid 'pattern' argument 
I send exemplary input file by email
